### ISSUE TITLE
WC3Data directory location

### ISSUE THREAD

**Issue by DerekX** [Skarmory/mdl-importer#3]
I can't find my "/Desktop/WC3Data directory". Where would it be after downloading Patch 1.30.2?

**Comment by Skarmory** [comment]
It's not a directory that comes with the game, it's just an intermediate place for the script to use because all the asset paths in the MDL data are relative. You can change it to whatever you like.

You just have to put the asset files for the model you want to view (with the MDX converted to MDL and BLP converted to PNG) into this intermediate directory in the same structure as they would be found in the MPQ.

**Comment by DerekX** [comment]
So I could just create that intermediate directory myself?

**Comment by DerekX** [comment]
Alright I'm actually having a problem with the game itself. Blizzard CustServ will have to help me there. Keep this issue open for a further update.

**Comment by DerekX** [comment]
This is a very inconvenient script, having to use an intermediate like this. Consider an improvement so that it doesn't...
